namespace SlearningWS
{//------------------------------------------------------------------------------
 // <auto-generated>
 //     Este código fue generado por una herramienta.
 //     Versión de runtime:4.0.30319.42000
 //
 //     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
 //     se vuelve a generar el código.
 // </auto-generated>
 //------------------------------------------------------------------------------

    using System;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Web.Services;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;

    // 
    // Este código fuente fue generado automáticamente por wsdl, Versión=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "ServidorPortBinding", Namespace = "http://servidor.utng.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(personaModelo))]
    public partial class ServidorService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback loginOperationCompleted;

        private System.Threading.SendOrPostCallback getArchivosAlumnosOperationCompleted;

        private System.Threading.SendOrPostCallback agregaActualizaArchivoOperationCompleted;

        private System.Threading.SendOrPostCallback getActividadOperationCompleted;

        private System.Threading.SendOrPostCallback eliminaCursoOperationCompleted;

        private System.Threading.SendOrPostCallback agregaActividadOperationCompleted;

        private System.Threading.SendOrPostCallback registroOperationCompleted;

        private System.Threading.SendOrPostCallback getArchivoOperationCompleted;

        private System.Threading.SendOrPostCallback agregaTemaOperationCompleted;

        private System.Threading.SendOrPostCallback getPorcentajeOperationCompleted;

        private System.Threading.SendOrPostCallback eliminaTemaOperationCompleted;

        private System.Threading.SendOrPostCallback getTemaOperationCompleted;

        private System.Threading.SendOrPostCallback agregaCursoOperationCompleted;

        /// <remarks/>
        public ServidorService()
        {
            this.Url = "http://192.168.0.26:8080/SLearningWS/slearningWS";
        }

        /// <remarks/>
        public event loginCompletedEventHandler loginCompleted;

        /// <remarks/>
        public event getArchivosAlumnosCompletedEventHandler getArchivosAlumnosCompleted;

        /// <remarks/>
        public event agregaActualizaArchivoCompletedEventHandler agregaActualizaArchivoCompleted;

        /// <remarks/>
        public event getActividadCompletedEventHandler getActividadCompleted;

        /// <remarks/>
        public event eliminaCursoCompletedEventHandler eliminaCursoCompleted;

        /// <remarks/>
        public event agregaActividadCompletedEventHandler agregaActividadCompleted;

        /// <remarks/>
        public event registroCompletedEventHandler registroCompleted;

        /// <remarks/>
        public event getArchivoCompletedEventHandler getArchivoCompleted;

        /// <remarks/>
        public event agregaTemaCompletedEventHandler agregaTemaCompleted;

        /// <remarks/>
        public event getPorcentajeCompletedEventHandler getPorcentajeCompleted;

        /// <remarks/>
        public event eliminaTemaCompletedEventHandler eliminaTemaCompleted;

        /// <remarks/>
        public event getTemaCompletedEventHandler getTemaCompleted;

        /// <remarks/>
        public event agregaCursoCompletedEventHandler agregaCursoCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://servidor.utng.com/", ResponseNamespace = "http://servidor.utng.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public usuarioModelo login([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] bool arg2)
        {
            object[] results = this.Invoke("login", new object[] {
                    arg0,
                    arg1,
                    arg2});
            return ((usuarioModelo)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult Beginlogin(string arg0, string arg1, bool arg2, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("login", new object[] {
                    arg0,
                    arg1,
                    arg2}, callback, asyncState);
        }

        /// <remarks/>
        public usuarioModelo Endlogin(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((usuarioModelo)(results[0]));
        }

        /// <remarks/>
        public void loginAsync(string arg0, string arg1, bool arg2)
        {
            this.loginAsync(arg0, arg1, arg2, null);
        }

        /// <remarks/>
        public void loginAsync(string arg0, string arg1, bool arg2, object userState)
        {
            if ((this.loginOperationCompleted == null))
            {
                this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
            }
            this.InvokeAsync("login", new object[] {
                    arg0,
                    arg1,
                    arg2}, this.loginOperationCompleted, userState);
        }

        private void OnloginOperationCompleted(object arg)
        {
            if ((this.loginCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://servidor.utng.com/", ResponseNamespace = "http://servidor.utng.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public archivoModelo[] getArchivosAlumnos([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] int arg0)
        {
            object[] results = this.Invoke("getArchivosAlumnos", new object[] {
                    arg0});
            return ((archivoModelo[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetArchivosAlumnos(int arg0, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getArchivosAlumnos", new object[] {
                    arg0}, callback, asyncState);
        }

        /// <remarks/>
        public archivoModelo[] EndgetArchivosAlumnos(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((archivoModelo[])(results[0]));
        }

        /// <remarks/>
        public void getArchivosAlumnosAsync(int arg0)
        {
            this.getArchivosAlumnosAsync(arg0, null);
        }

        /// <remarks/>
        public void getArchivosAlumnosAsync(int arg0, object userState)
        {
            if ((this.getArchivosAlumnosOperationCompleted == null))
            {
                this.getArchivosAlumnosOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetArchivosAlumnosOperationCompleted);
            }
            this.InvokeAsync("getArchivosAlumnos", new object[] {
                    arg0}, this.getArchivosAlumnosOperationCompleted, userState);
        }

        private void OngetArchivosAlumnosOperationCompleted(object arg)
        {
            if ((this.getArchivosAlumnosCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getArchivosAlumnosCompleted(this, new getArchivosAlumnosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://servidor.utng.com/", ResponseNamespace = "http://servidor.utng.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool agregaActualizaArchivo([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] archivoModelo arg0)
        {
            object[] results = this.Invoke("agregaActualizaArchivo", new object[] {
                    arg0});
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginagregaActualizaArchivo(archivoModelo arg0, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("agregaActualizaArchivo", new object[] {
                    arg0}, callback, asyncState);
        }

        /// <remarks/>
        public bool EndagregaActualizaArchivo(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void agregaActualizaArchivoAsync(archivoModelo arg0)
        {
            this.agregaActualizaArchivoAsync(arg0, null);
        }

        /// <remarks/>
        public void agregaActualizaArchivoAsync(archivoModelo arg0, object userState)
        {
            if ((this.agregaActualizaArchivoOperationCompleted == null))
            {
                this.agregaActualizaArchivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnagregaActualizaArchivoOperationCompleted);
            }
            this.InvokeAsync("agregaActualizaArchivo", new object[] {
                    arg0}, this.agregaActualizaArchivoOperationCompleted, userState);
        }

        private void OnagregaActualizaArchivoOperationCompleted(object arg)
        {
            if ((this.agregaActualizaArchivoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.agregaActualizaArchivoCompleted(this, new agregaActualizaArchivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://servidor.utng.com/", ResponseNamespace = "http://servidor.utng.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public actividadModelo[] getActividad([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] int arg0)
        {
            object[] results = this.Invoke("getActividad", new object[] {
                    arg0});
            return ((actividadModelo[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetActividad(int arg0, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getActividad", new object[] {
                    arg0}, callback, asyncState);
        }

        /// <remarks/>
        public actividadModelo[] EndgetActividad(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((actividadModelo[])(results[0]));
        }

        /// <remarks/>
        public void getActividadAsync(int arg0)
        {
            this.getActividadAsync(arg0, null);
        }

        /// <remarks/>
        public void getActividadAsync(int arg0, object userState)
        {
            if ((this.getActividadOperationCompleted == null))
            {
                this.getActividadOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetActividadOperationCompleted);
            }
            this.InvokeAsync("getActividad", new object[] {
                    arg0}, this.getActividadOperationCompleted, userState);
        }

        private void OngetActividadOperationCompleted(object arg)
        {
            if ((this.getActividadCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getActividadCompleted(this, new getActividadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://servidor.utng.com/", ResponseNamespace = "http://servidor.utng.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool eliminaCurso([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] cursoModelo arg0)
        {
            object[] results = this.Invoke("eliminaCurso", new object[] {
                    arg0});
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegineliminaCurso(cursoModelo arg0, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("eliminaCurso", new object[] {
                    arg0}, callback, asyncState);
        }

        /// <remarks/>
        public bool EndeliminaCurso(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void eliminaCursoAsync(cursoModelo arg0)
        {
            this.eliminaCursoAsync(arg0, null);
        }

        /// <remarks/>
        public void eliminaCursoAsync(cursoModelo arg0, object userState)
        {
            if ((this.eliminaCursoOperationCompleted == null))
            {
                this.eliminaCursoOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminaCursoOperationCompleted);
            }
            this.InvokeAsync("eliminaCurso", new object[] {
                    arg0}, this.eliminaCursoOperationCompleted, userState);
        }

        private void OneliminaCursoOperationCompleted(object arg)
        {
            if ((this.eliminaCursoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminaCursoCompleted(this, new eliminaCursoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://servidor.utng.com/", ResponseNamespace = "http://servidor.utng.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool agregaActividad([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] actividadModelo arg0)
        {
            object[] results = this.Invoke("agregaActividad", new object[] {
                    arg0});
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginagregaActividad(actividadModelo arg0, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("agregaActividad", new object[] {
                    arg0}, callback, asyncState);
        }

        /// <remarks/>
        public bool EndagregaActividad(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void agregaActividadAsync(actividadModelo arg0)
        {
            this.agregaActividadAsync(arg0, null);
        }

        /// <remarks/>
        public void agregaActividadAsync(actividadModelo arg0, object userState)
        {
            if ((this.agregaActividadOperationCompleted == null))
            {
                this.agregaActividadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnagregaActividadOperationCompleted);
            }
            this.InvokeAsync("agregaActividad", new object[] {
                    arg0}, this.agregaActividadOperationCompleted, userState);
        }

        private void OnagregaActividadOperationCompleted(object arg)
        {
            if ((this.agregaActividadCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.agregaActividadCompleted(this, new agregaActividadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://servidor.utng.com/", ResponseNamespace = "http://servidor.utng.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool registro([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] usuarioModelo arg0)
        {
            object[] results = this.Invoke("registro", new object[] {
                    arg0});
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult Beginregistro(usuarioModelo arg0, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("registro", new object[] {
                    arg0}, callback, asyncState);
        }

        /// <remarks/>
        public bool Endregistro(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void registroAsync(usuarioModelo arg0)
        {
            this.registroAsync(arg0, null);
        }

        /// <remarks/>
        public void registroAsync(usuarioModelo arg0, object userState)
        {
            if ((this.registroOperationCompleted == null))
            {
                this.registroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistroOperationCompleted);
            }
            this.InvokeAsync("registro", new object[] {
                    arg0}, this.registroOperationCompleted, userState);
        }

        private void OnregistroOperationCompleted(object arg)
        {
            if ((this.registroCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registroCompleted(this, new registroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://servidor.utng.com/", ResponseNamespace = "http://servidor.utng.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public archivoModelo getArchivo([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] int arg0, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] int arg1)
        {
            object[] results = this.Invoke("getArchivo", new object[] {
                    arg0,
                    arg1});
            return ((archivoModelo)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetArchivo(int arg0, int arg1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getArchivo", new object[] {
                    arg0,
                    arg1}, callback, asyncState);
        }

        /// <remarks/>
        public archivoModelo EndgetArchivo(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((archivoModelo)(results[0]));
        }

        /// <remarks/>
        public void getArchivoAsync(int arg0, int arg1)
        {
            this.getArchivoAsync(arg0, arg1, null);
        }

        /// <remarks/>
        public void getArchivoAsync(int arg0, int arg1, object userState)
        {
            if ((this.getArchivoOperationCompleted == null))
            {
                this.getArchivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetArchivoOperationCompleted);
            }
            this.InvokeAsync("getArchivo", new object[] {
                    arg0,
                    arg1}, this.getArchivoOperationCompleted, userState);
        }

        private void OngetArchivoOperationCompleted(object arg)
        {
            if ((this.getArchivoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getArchivoCompleted(this, new getArchivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://servidor.utng.com/", ResponseNamespace = "http://servidor.utng.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool agregaTema([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] temaModelo arg0)
        {
            object[] results = this.Invoke("agregaTema", new object[] {
                    arg0});
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginagregaTema(temaModelo arg0, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("agregaTema", new object[] {
                    arg0}, callback, asyncState);
        }

        /// <remarks/>
        public bool EndagregaTema(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void agregaTemaAsync(temaModelo arg0)
        {
            this.agregaTemaAsync(arg0, null);
        }

        /// <remarks/>
        public void agregaTemaAsync(temaModelo arg0, object userState)
        {
            if ((this.agregaTemaOperationCompleted == null))
            {
                this.agregaTemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnagregaTemaOperationCompleted);
            }
            this.InvokeAsync("agregaTema", new object[] {
                    arg0}, this.agregaTemaOperationCompleted, userState);
        }

        private void OnagregaTemaOperationCompleted(object arg)
        {
            if ((this.agregaTemaCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.agregaTemaCompleted(this, new agregaTemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://servidor.utng.com/", ResponseNamespace = "http://servidor.utng.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double getPorcentaje([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] int arg0)
        {
            object[] results = this.Invoke("getPorcentaje", new object[] {
                    arg0});
            return ((double)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetPorcentaje(int arg0, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getPorcentaje", new object[] {
                    arg0}, callback, asyncState);
        }

        /// <remarks/>
        public double EndgetPorcentaje(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((double)(results[0]));
        }

        /// <remarks/>
        public void getPorcentajeAsync(int arg0)
        {
            this.getPorcentajeAsync(arg0, null);
        }

        /// <remarks/>
        public void getPorcentajeAsync(int arg0, object userState)
        {
            if ((this.getPorcentajeOperationCompleted == null))
            {
                this.getPorcentajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPorcentajeOperationCompleted);
            }
            this.InvokeAsync("getPorcentaje", new object[] {
                    arg0}, this.getPorcentajeOperationCompleted, userState);
        }

        private void OngetPorcentajeOperationCompleted(object arg)
        {
            if ((this.getPorcentajeCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPorcentajeCompleted(this, new getPorcentajeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://servidor.utng.com/", ResponseNamespace = "http://servidor.utng.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool eliminaTema([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] temaModelo arg0)
        {
            object[] results = this.Invoke("eliminaTema", new object[] {
                    arg0});
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegineliminaTema(temaModelo arg0, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("eliminaTema", new object[] {
                    arg0}, callback, asyncState);
        }

        /// <remarks/>
        public bool EndeliminaTema(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void eliminaTemaAsync(temaModelo arg0)
        {
            this.eliminaTemaAsync(arg0, null);
        }

        /// <remarks/>
        public void eliminaTemaAsync(temaModelo arg0, object userState)
        {
            if ((this.eliminaTemaOperationCompleted == null))
            {
                this.eliminaTemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminaTemaOperationCompleted);
            }
            this.InvokeAsync("eliminaTema", new object[] {
                    arg0}, this.eliminaTemaOperationCompleted, userState);
        }

        private void OneliminaTemaOperationCompleted(object arg)
        {
            if ((this.eliminaTemaCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminaTemaCompleted(this, new eliminaTemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://servidor.utng.com/", ResponseNamespace = "http://servidor.utng.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public temaModelo[] getTema([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] int arg0)
        {
            object[] results = this.Invoke("getTema", new object[] {
                    arg0});
            return ((temaModelo[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetTema(int arg0, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getTema", new object[] {
                    arg0}, callback, asyncState);
        }

        /// <remarks/>
        public temaModelo[] EndgetTema(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((temaModelo[])(results[0]));
        }

        /// <remarks/>
        public void getTemaAsync(int arg0)
        {
            this.getTemaAsync(arg0, null);
        }

        /// <remarks/>
        public void getTemaAsync(int arg0, object userState)
        {
            if ((this.getTemaOperationCompleted == null))
            {
                this.getTemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTemaOperationCompleted);
            }
            this.InvokeAsync("getTema", new object[] {
                    arg0}, this.getTemaOperationCompleted, userState);
        }

        private void OngetTemaOperationCompleted(object arg)
        {
            if ((this.getTemaCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTemaCompleted(this, new getTemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://servidor.utng.com/", ResponseNamespace = "http://servidor.utng.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool agregaCurso([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] cursoModelo arg0)
        {
            object[] results = this.Invoke("agregaCurso", new object[] {
                    arg0});
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginagregaCurso(cursoModelo arg0, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("agregaCurso", new object[] {
                    arg0}, callback, asyncState);
        }

        /// <remarks/>
        public bool EndagregaCurso(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void agregaCursoAsync(cursoModelo arg0)
        {
            this.agregaCursoAsync(arg0, null);
        }

        /// <remarks/>
        public void agregaCursoAsync(cursoModelo arg0, object userState)
        {
            if ((this.agregaCursoOperationCompleted == null))
            {
                this.agregaCursoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnagregaCursoOperationCompleted);
            }
            this.InvokeAsync("agregaCurso", new object[] {
                    arg0}, this.agregaCursoOperationCompleted, userState);
        }

        private void OnagregaCursoOperationCompleted(object arg)
        {
            if ((this.agregaCursoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.agregaCursoCompleted(this, new agregaCursoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://servidor.utng.com/")]
    public partial class usuarioModelo : personaModelo
    {

        private string contrasenaField;

        private string correoField;

        private cursoModelo[] cursosField;

        private byte[] imagenField;

        private string nicknameField;

        private rolModelo rolField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrasena
        {
            get
            {
                return this.contrasenaField;
            }
            set
            {
                this.contrasenaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo
        {
            get
            {
                return this.correoField;
            }
            set
            {
                this.correoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cursos", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public cursoModelo[] cursos
        {
            get
            {
                return this.cursosField;
            }
            set
            {
                this.cursosField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "base64Binary")]
        public byte[] imagen
        {
            get
            {
                return this.imagenField;
            }
            set
            {
                this.imagenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nickname
        {
            get
            {
                return this.nicknameField;
            }
            set
            {
                this.nicknameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public rolModelo rol
        {
            get
            {
                return this.rolField;
            }
            set
            {
                this.rolField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://servidor.utng.com/")]
    public partial class cursoModelo
    {

        private int anioField;

        private int idCursoField;

        private string nombreField;

        private string periodoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int anio
        {
            get
            {
                return this.anioField;
            }
            set
            {
                this.anioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCurso
        {
            get
            {
                return this.idCursoField;
            }
            set
            {
                this.idCursoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string periodo
        {
            get
            {
                return this.periodoField;
            }
            set
            {
                this.periodoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://servidor.utng.com/")]
    public partial class temaModelo
    {

        private cursoModelo cursoField;

        private int idTemaField;

        private string nombreField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public cursoModelo curso
        {
            get
            {
                return this.cursoField;
            }
            set
            {
                this.cursoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTema
        {
            get
            {
                return this.idTemaField;
            }
            set
            {
                this.idTemaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://servidor.utng.com/")]
    public partial class actividadModelo
    {

        private string descripcionField;

        private string fechaFinField;

        private string fechaInicioField;

        private string horaFinField;

        private string horaInicioField;

        private int idActividadField;

        private string nombreField;

        private temaModelo temaField;

        private double valorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaFin
        {
            get
            {
                return this.fechaFinField;
            }
            set
            {
                this.fechaFinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaInicio
        {
            get
            {
                return this.fechaInicioField;
            }
            set
            {
                this.fechaInicioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string horaFin
        {
            get
            {
                return this.horaFinField;
            }
            set
            {
                this.horaFinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string horaInicio
        {
            get
            {
                return this.horaInicioField;
            }
            set
            {
                this.horaInicioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idActividad
        {
            get
            {
                return this.idActividadField;
            }
            set
            {
                this.idActividadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public temaModelo tema
        {
            get
            {
                return this.temaField;
            }
            set
            {
                this.temaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double valor
        {
            get
            {
                return this.valorField;
            }
            set
            {
                this.valorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://servidor.utng.com/")]
    public partial class archivoModelo
    {

        private actividadModelo actividadField;

        private int archivoIdField;

        private byte[] bufferArchivoField;

        private string extensionField;

        private string nombreField;

        private usuarioModelo usuarioField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public actividadModelo actividad
        {
            get
            {
                return this.actividadField;
            }
            set
            {
                this.actividadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int archivoId
        {
            get
            {
                return this.archivoIdField;
            }
            set
            {
                this.archivoIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "base64Binary")]
        public byte[] bufferArchivo
        {
            get
            {
                return this.bufferArchivoField;
            }
            set
            {
                this.bufferArchivoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public usuarioModelo usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://servidor.utng.com/")]
    public partial class rolModelo
    {

        private string descripcionField;

        private int idRolField;

        private string nombreField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idRol
        {
            get
            {
                return this.idRolField;
            }
            set
            {
                this.idRolField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(usuarioModelo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://servidor.utng.com/")]
    public partial class personaModelo
    {

        private string fechaNacimientoField;

        private int idPersonaField;

        private string nombreField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaNacimiento
        {
            get
            {
                return this.fechaNacimientoField;
            }
            set
            {
                this.fechaNacimientoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPersona
        {
            get
            {
                return this.idPersonaField;
            }
            set
            {
                this.idPersonaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public usuarioModelo Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((usuarioModelo)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void getArchivosAlumnosCompletedEventHandler(object sender, getArchivosAlumnosCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getArchivosAlumnosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getArchivosAlumnosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public archivoModelo[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((archivoModelo[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void agregaActualizaArchivoCompletedEventHandler(object sender, agregaActualizaArchivoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class agregaActualizaArchivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal agregaActualizaArchivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void getActividadCompletedEventHandler(object sender, getActividadCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getActividadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getActividadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public actividadModelo[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((actividadModelo[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void eliminaCursoCompletedEventHandler(object sender, eliminaCursoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminaCursoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal eliminaCursoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void agregaActividadCompletedEventHandler(object sender, agregaActividadCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class agregaActividadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal agregaActividadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void registroCompletedEventHandler(object sender, registroCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal registroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void getArchivoCompletedEventHandler(object sender, getArchivoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getArchivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getArchivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public archivoModelo Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((archivoModelo)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void agregaTemaCompletedEventHandler(object sender, agregaTemaCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class agregaTemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal agregaTemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void getPorcentajeCompletedEventHandler(object sender, getPorcentajeCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPorcentajeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getPorcentajeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public double Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void eliminaTemaCompletedEventHandler(object sender, eliminaTemaCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminaTemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal eliminaTemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void getTemaCompletedEventHandler(object sender, getTemaCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getTemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public temaModelo[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((temaModelo[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void agregaCursoCompletedEventHandler(object sender, agregaCursoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class agregaCursoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal agregaCursoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}